services:
  latex:
    image: danteev/texlive:latest
    container_name: latex
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: tail -f /dev/null
    restart: unless-stopped
